### ISSUE TITLE
Configurable date hierarchy

### ISSUE THREAD

**Issue by rstml** [jkausti/target-s3#9]
It seems that the current date hierarchy has hardcoded format:

https://github.com/jkausti/target-s3/blob/12cf3f7060a138655cb4179ffbfa047b6a534a12/target_s3/sinks.py#L52-L53

However, different levels of granularity may be required for different data volumes. E.g., in some cases month level will be sufficient in others hourly resolution might be required.

It would be great if we could cusotmise it. In my case, I need month level.

**Comment by rstml** [comment]
I may be able to create PR but have a question regarding implementation.

Would it be better to add a new variable e.g.:

```js
folder_structure_level : {'year', 'month', 'day', 'hour', 'minute'}
```
or extend `folder_structure` with:

```js
{'date_hierarchy_year', 'date_hierarchy_month', 'date_hierarchy_day', 'date_hierarchy_hour', 'date_hierarchy_minute'}
```

**Comment by rstml** [comment]
quick update: i ended up using another sink that already supports that.

**Comment by jkausti** [comment]
Hi @rstml, thanks for raising an issue. Glad you found a way to make your use case work. I am not actively using this target myself and I don't plan to actively maintain it anymore. I think [this sink](https://hub.meltano.com/loaders/target-s3/) should definitely be used instead, as it completely covers the functionality of this one and much more. It also seems to be actively maintained.

I'll close this issue since you found a working solution.
